### ISSUE TITLE
Github thinks theres more Python than Go!

### ISSUE THREAD

**Issue by zeebo** [zeebo/goci#1]
It upsets me that because I have to package a virtualenv for installing hg + bzr that  the most dominant language of this project is Python.

Please fix by writing more Go code!

**Comment by nathany** [comment]
if you are using @kr's [build pack](https://github.com/kr/heroku-buildpack-go) for Heroku, it should take care of this for you

**Comment by kr** [comment]
I suspect this project needs VCS tools available at runtime, not just
during deployment to heroku. The buildpack doesn't put those tools
(or the Go compiler) in the slug, unfortunately.

It might not be too hard to fork the plugin and add that behavior.

**Comment by zeebo** [comment]
It is indeed true that the hg + bzr deps are runtime dependencies. I'm not sure it's worth it to fork the buildpack. :)

I think I'm just gonna close this joke bug.
