### ISSUE TITLE
Github readme image caching

### ISSUE THREAD

**Issue by rif** [zeebo/goci#10]
I believe that if you serve the build status image from a https server it will not be cached by github. 

This would solve the stale status image problem.

**Comment by zeebo** [comment]
Unfortunately doing https on heroku will either have an incorrect domain (using heroku's ssl cert) or cost some money, and I'm trying to keep it free. :(

I might be able to have an https cert thats valid for goci.herokuapp.com and we could change the domain for the image. I'll look into it.

**Comment by zeebo** [comment]
No config necessary:

https://goci.herokuapp.com/project/image/import/path

**Comment by rif** [comment]
You can just advise users on the http://goci.me/how page to use https:

https://goci.me/project/image/<import path>

**Comment by zeebo** [comment]
Done.
