### ISSUE TITLE
You don't need to set GOROOT, really

### ISSUE THREAD

**Issue by nathany** [zeebo/goci#14]
http://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really

```
=== RUN TestSingleImport
--- FAIL: TestSingleImport (0.00 seconds)
panic: key not found in environment: GOROOT [recovered]
    panic: key not found in environment: GOROOT

goroutine 5 [running]:
testing.func·004()
    /go/golang/src/pkg/testing/testing.go:348 +0xcd
github.com/zeebo/goci/builder.mustEnv(0x2a3cc0, 0x6, 0x1, 0x0)
    /go/project/src/github.com/zeebo/goci/builder/helper.go:19 +0xbf
github.com/zeebo/goci/builder.New(0x2a9800, 0x6, 0x2a8980, 0x5, 0x2a0e40, ...)
    /go/project/src/github.com/zeebo/goci/builder/builder.go:62 +0xbf
github.com/zeebo/goci/builder.TestSingleImport(0xc2000c9e10)
    /go/project/src/github.com/zeebo/goci/builder/builder_test.go:15 +0xa5
```

**Comment by zeebo** [comment]
So the builder package is designed to be able to build with multiple versions of Go. Since I'm also unzipping into a nonstandard location, it is required to have GOROOT set.

**Comment by nathany** [comment]
Okay. Btw, that was on the master branch. Should I be looking at the live branch instead?

**Comment by zeebo** [comment]
The live branch contains the code that's running on heroku now. The master branch went through a half finished rewrite.

GoCI is in a sad state due to my becoming employed. :(
