### ISSUE TITLE
goci.me is stuck

### ISSUE THREAD

**Issue by speter** [zeebo/goci#17]
Thank you for the great system and service! Unfortunately it seems that builds on goci.me have stalled and not making progress since about June 15. Could you have a look at it?

**Comment by zeebo** [comment]
Well, I updated it to use go1.3 and gave it a couple kicks and it didn't appear to help. I think at this point the service has outlived it's usefulness and people should just use travis-ci. They have much better support than this and it's actively maintained.

 Sorry for the disappointing response!

**Comment by speter** [comment]
That's perfectly reasonable. (Although perhaps leaving a note on the goci.me site would make it less surprising for other users.)

Thanks again for the great service in the past 2 years!
