### ISSUE TITLE
Display "Date" column with local timezone

### ISSUE THREAD

**Issue by antage** [zeebo/goci#4]
"Date" column shows time in UTC but local timezone (using javascript) is more preferred.

**Comment by zeebo** [comment]
Good idea. Do you know of any javascript libraries to help with this off the top of your head?

**Comment by antage** [comment]
Try following code:

``` javascript
$("table.table > tbody > tr > td:nth-child(3)").each(function (_, el) {
    var $el = $(el),
         d = Date.parse($el.html());
         localizedTime = new Date(d - (new Date(d)).getTimezoneOffset() * 60 * 1000).toString();
    $el.html(localizedTime); 
})
```

Also take a look at http://code.google.com/p/datejs
