### ISSUE TITLE
cgrates build hangs

### ISSUE THREAD

**Issue by rif** [zeebo/goci#7]
Hi I am the creator of  github.com/cgrates/cgrates. Some old build/tests of my project are stuck on you queue. Please kill them so the new (improved :) ones can run and hopefully pass.

Thank you,
rif

**Comment by rif** [comment]
Ah, sorry for the stuck ones (it was my fault).

Anyhow maybe a timeout and kill would be a good idea.

**Comment by zeebo** [comment]
It should have a timeout and kill. I had some projects that also got stuck sometime. I'm currently in the process of doing a major rewrite so I haven't investigated too deeply why it happens.

In any case, the queue has been emptied. Let me know if this happens again. Hopefully we won't have to deal with it for too much longer.

**Comment by rif** [comment]
Thank you, now the status on the goci.me is passed but it says there are no tests and also the image on the github readme (from my project) says failed.

**Comment by zeebo** [comment]
The image on github is cached. If you go to http://goci.me/project/image/github.com/cgrates/cgrates you can see it says it's passed. I don't know how to fix that.

I'll look into why it says there are no tests.

**Comment by zeebo** [comment]
How did you request that package be tested? What hook did you use?

**Comment by rif** [comment]
Thank, goci.me is a great help. I discovered it today after reading this: http://shadynasty.biz/blog/2012/07/30/quick-and-clean-in-go/ .And I am exited about it :)

Right now I run: curl -X GET http://goci.me/hooks/go/github.com/cgrates/cgrates

**Comment by zeebo** [comment]
In that case you're testing a specific import path. That import path has no tests. :)

**Comment by rif** [comment]
I'll make a commit/push to github.

**Comment by rif** [comment]
Is it stuck again?

Side note: when you click on queue link you get a # in the address bar.

**Comment by zeebo** [comment]
Looks like it. I might have to fix this one :)

**Comment by zeebo** [comment]
Gimme a min to look into it. This one is probably going to be pretty hairy.

**Comment by rif** [comment]
It's 1am over here (Romania) so I'll hit the bed and check back in the morning.

**Comment by zeebo** [comment]
I believe I have it fixed. The issue was caused when there were multiple builds and one of them had a compile error. The channel managing the build wasn't signaled that the tests wouldn't be scheduled and so it waited for them to be completed forever. Let me know.

**Comment by rif** [comment]
Now it works great. Even the github readme icon changes almost realtime.

Thank you and all the best,
rif

**Comment by zeebo** [comment]
Fixed by 28b611d178241ef17fe12755830c40a9294c705c

**Comment by rif** [comment]
Idea: create a api to report the number of tests passed/failed per project. You just have to grep the output for PASS/FAIL.

Near the PASSED icon I think that the number of tests would look very good.

**Comment by zeebo** [comment]
An api to inspect the state of the system and the history of tests isn't a bad idea. I'll make a feature enhancement issue for it and keep it in mind while coding. Thanks.
